"""Hand-curated data for the 111 staple exercises: ordered swaps and cues.

Swap codes: d = same_pattern_diff_kit, e = easier_regression,
            h = harder_progression,   m = same_muscle
Swap lists are ordered best-first. Cues are our own wording.
"""

SWAPS = {
 # ---------------- squat
 "Barbell_Squat": "Hack_Squat d, Leg_Press d, Smith_Machine_Squat d, Front_Squat_Clean_Grip m, Box_Squat m, Goblet_Squat e",
 "Barbell_Full_Squat": "Barbell_Squat m, Front_Squat_Clean_Grip m, Hack_Squat d, Leg_Press d, Goblet_Squat e",
 "Front_Squat_Clean_Grip": "Barbell_Squat m, Hack_Squat d, Front_Squats_With_Two_Kettlebells d, Leg_Press d, Goblet_Squat e",
 "Goblet_Squat": "Dumbbell_Squat m, Leg_Press d, Front_Squats_With_Two_Kettlebells h, Barbell_Squat h, Bodyweight_Squat e",
 "Leg_Press": "Hack_Squat m, Narrow_Stance_Leg_Press m, Smith_Machine_Squat d, Barbell_Squat d, Goblet_Squat d",
 "Hack_Squat": "Leg_Press m, Smith_Machine_Squat d, Barbell_Squat d, Narrow_Stance_Hack_Squats m, Goblet_Squat e",
 "Smith_Machine_Squat": "Hack_Squat d, Leg_Press d, Barbell_Squat h, Goblet_Squat d",
 "Bodyweight_Squat": "Chair_Squat e, Goblet_Squat h, Dumbbell_Squat h, Leg_Press d",
 "Dumbbell_Squat": "Goblet_Squat m, Leg_Press d, Barbell_Squat h, Bodyweight_Squat e",
 "Box_Squat": "Barbell_Squat m, Dumbbell_Squat_To_A_Bench d, Leg_Press d, Goblet_Squat e",
 # ---------------- hinge
 "Barbell_Deadlift": "Trap_Bar_Deadlift d, Sumo_Deadlift m, Romanian_Deadlift m, Rack_Pulls e, Stiff-Legged_Dumbbell_Deadlift d",
 "Romanian_Deadlift": "Stiff-Legged_Dumbbell_Deadlift d, Stiff-Legged_Barbell_Deadlift m, Good_Morning m, Kettlebell_One-Legged_Deadlift m, Hyperextensions_Back_Extensions e",
 "Trap_Bar_Deadlift": "Barbell_Deadlift d, Sumo_Deadlift d, Leverage_Deadlift d, Rack_Pulls e, Stiff-Legged_Dumbbell_Deadlift d",
 "Stiff-Legged_Dumbbell_Deadlift": "Romanian_Deadlift d, Kettlebell_One-Legged_Deadlift m, Good_Morning d, Pull_Through d, Hyperextensions_Back_Extensions e",
 "Barbell_Hip_Thrust": "Barbell_Glute_Bridge m, Smith_Machine_Hip_Raise d, Pull_Through d, Single_Leg_Glute_Bridge e, Butt_Lift_Bridge e",
 "Barbell_Glute_Bridge": "Barbell_Hip_Thrust h, Smith_Machine_Hip_Raise d, Pull_Through d, Single_Leg_Glute_Bridge e, Butt_Lift_Bridge e",
 "Single_Leg_Glute_Bridge": "Butt_Lift_Bridge e, Physioball_Hip_Bridge d, Barbell_Glute_Bridge h, Barbell_Hip_Thrust h",
 "Hyperextensions_Back_Extensions": "Hyperextensions_With_No_Hyperextension_Bench d, Reverse_Hyperextension m, Weighted_Ball_Hyperextension m, Good_Morning h, Romanian_Deadlift h",
 "Good_Morning": "Romanian_Deadlift m, Stiff-Legged_Dumbbell_Deadlift d, Pull_Through d, Band_Good_Morning e, Hyperextensions_Back_Extensions e",
 "One-Arm_Kettlebell_Swings": "Pull_Through d, Band_Good_Morning_Pull_Through d, Stiff-Legged_Dumbbell_Deadlift d, Romanian_Deadlift d, Barbell_Hip_Thrust m",
 "Sumo_Deadlift": "Barbell_Deadlift m, Trap_Bar_Deadlift d, Romanian_Deadlift m, Rack_Pulls e, Plie_Dumbbell_Squat e",
 "Pull_Through": "One-Arm_Kettlebell_Swings d, Band_Good_Morning_Pull_Through d, Barbell_Glute_Bridge d, Hyperextensions_Back_Extensions m, Romanian_Deadlift h",
 "Kettlebell_One-Legged_Deadlift": "Stiff-Legged_Dumbbell_Deadlift e, Romanian_Deadlift d, Good_Morning d, Single_Leg_Glute_Bridge e",
 # ---------------- lunge
 "Dumbbell_Lunges": "Dumbbell_Rear_Lunge m, Dumbbell_Step_Ups m, Barbell_Lunge d, Split_Squat_with_Dumbbells e, Bodyweight_Walking_Lunge e, Barbell_Walking_Lunge h",
 "Barbell_Walking_Lunge": "Dumbbell_Lunges d, Barbell_Lunge m, Barbell_Step_Ups m, Split_Squat_with_Dumbbells d, Bodyweight_Walking_Lunge e",
 "Bodyweight_Walking_Lunge": "Elevated_Back_Lunge m, Dumbbell_Lunges h, Dumbbell_Rear_Lunge h, Bodyweight_Squat e",
 "Split_Squat_with_Dumbbells": "Smith_Single-Leg_Split_Squat d, Suspended_Split_Squat d, Dumbbell_Rear_Lunge m, Dumbbell_Step_Ups m, Dumbbell_Lunges h",
 "Dumbbell_Step_Ups": "Barbell_Step_Ups d, Split_Squat_with_Dumbbells m, Dumbbell_Lunges m, Step-up_with_Knee_Raise e",
 "Dumbbell_Rear_Lunge": "Dumbbell_Lunges m, Barbell_Lunge d, Elevated_Back_Lunge h, Split_Squat_with_Dumbbells e, Bodyweight_Walking_Lunge e",
 "Barbell_Lunge": "Dumbbell_Lunges d, Smith_Single-Leg_Split_Squat d, Barbell_Step_Ups m, Barbell_Walking_Lunge h, Split_Squat_with_Dumbbells d",
 # ---------------- push_h
 "Barbell_Bench_Press_-_Medium_Grip": "Dumbbell_Bench_Press d, Machine_Bench_Press d, Smith_Machine_Bench_Press d, Leverage_Chest_Press d, Barbell_Incline_Bench_Press_-_Medium_Grip m, Pushups e",
 "Dumbbell_Bench_Press": "Barbell_Bench_Press_-_Medium_Grip d, Machine_Bench_Press d, Dumbbell_Bench_Press_with_Neutral_Grip m, Incline_Dumbbell_Press m, Cable_Chest_Press d, Pushups e",
 "Incline_Dumbbell_Press": "Barbell_Incline_Bench_Press_-_Medium_Grip d, Leverage_Incline_Chest_Press d, Smith_Machine_Incline_Bench_Press d, Incline_Cable_Chest_Press d, Dumbbell_Bench_Press m",
 "Barbell_Incline_Bench_Press_-_Medium_Grip": "Incline_Dumbbell_Press d, Smith_Machine_Incline_Bench_Press d, Leverage_Incline_Chest_Press d, Barbell_Bench_Press_-_Medium_Grip m",
 "Pushups": "Push-Ups_-_Close_Triceps_Position m, Dumbbell_Bench_Press d, Machine_Bench_Press d, Incline_Push-Up e, Push-Ups_With_Feet_Elevated h",
 "Incline_Push-Up": "Incline_Push-Up_Medium m, Machine_Bench_Press d, Cable_Chest_Press d, Pushups h",
 "Machine_Bench_Press": "Leverage_Chest_Press m, Dumbbell_Bench_Press d, Smith_Machine_Bench_Press d, Cable_Chest_Press d, Pushups d",
 "Cable_Crossover": "Low_Cable_Crossover m, Flat_Bench_Cable_Flyes m, Butterfly d, Dumbbell_Flyes d, Incline_Cable_Flye m",
 "Dumbbell_Flyes": "Cable_Crossover d, Butterfly d, Flat_Bench_Cable_Flyes d, Incline_Dumbbell_Flyes m",
 "Dips_-_Chest_Version": "Dip_Machine d, Decline_Barbell_Bench_Press d, Dumbbell_Bench_Press d, Pushups e, Ring_Dips h",
 "Close-Grip_Barbell_Bench_Press": "Close-Grip_Dumbbell_Press d, Smith_Machine_Close-Grip_Bench_Press d, JM_Press m, Push-Ups_-_Close_Triceps_Position e, Dips_-_Triceps_Version m",
 "Leverage_Chest_Press": "Machine_Bench_Press m, Dumbbell_Bench_Press d, Cable_Chest_Press d, Barbell_Bench_Press_-_Medium_Grip d, Pushups d",
 "Butterfly": "Cable_Crossover d, Dumbbell_Flyes d, Flat_Bench_Cable_Flyes d, Incline_Cable_Flye d",
 "Smith_Machine_Bench_Press": "Barbell_Bench_Press_-_Medium_Grip d, Machine_Bench_Press d, Dumbbell_Bench_Press d, Leverage_Chest_Press d",
 # ---------------- push_v
 "Standing_Military_Press": "Seated_Barbell_Military_Press m, Dumbbell_Shoulder_Press d, Machine_Shoulder_Military_Press d, Smith_Machine_Overhead_Shoulder_Press d, Landmine_Linear_Jammer d",
 "Dumbbell_Shoulder_Press": "Seated_Dumbbell_Press m, Arnold_Dumbbell_Press m, Standing_Military_Press d, Machine_Shoulder_Military_Press d, Two-Arm_Kettlebell_Military_Press d, Landmine_Linear_Jammer d",
 "Seated_Dumbbell_Press": "Dumbbell_Shoulder_Press m, Arnold_Dumbbell_Press m, Machine_Shoulder_Military_Press d, Seated_Barbell_Military_Press d, Seated_Cable_Shoulder_Press d",
 "Machine_Shoulder_Military_Press": "Leverage_Shoulder_Press m, Seated_Dumbbell_Press d, Smith_Machine_Overhead_Shoulder_Press d, Seated_Cable_Shoulder_Press d",
 "Arnold_Dumbbell_Press": "Dumbbell_Shoulder_Press m, Seated_Dumbbell_Press m, Kettlebell_Arnold_Press d, Machine_Shoulder_Military_Press d",
 "Landmine_Linear_Jammer": "Single-Arm_Linear_Jammer m, Dumbbell_Shoulder_Press d, Machine_Shoulder_Military_Press d, Standing_Military_Press d",
 # ---------------- pull_v
 "Pullups": "Chin-Up m, Wide-Grip_Lat_Pulldown d, Close-Grip_Front_Lat_Pulldown d, Band_Assisted_Pull-Up e, Weighted_Pull_Ups h",
 "Chin-Up": "Pullups m, Underhand_Cable_Pulldowns d, Close-Grip_Front_Lat_Pulldown d, Band_Assisted_Pull-Up e, Weighted_Pull_Ups h",
 "Wide-Grip_Lat_Pulldown": "Close-Grip_Front_Lat_Pulldown m, V-Bar_Pulldown m, Full_Range-Of-Motion_Lat_Pulldown m, Underhand_Cable_Pulldowns m, Band_Assisted_Pull-Up d, Pullups h",
 "Close-Grip_Front_Lat_Pulldown": "Wide-Grip_Lat_Pulldown m, V-Bar_Pulldown m, Underhand_Cable_Pulldowns m, Band_Assisted_Pull-Up d, Chin-Up h",
 "Band_Assisted_Pull-Up": "Wide-Grip_Lat_Pulldown d, Close-Grip_Front_Lat_Pulldown d, Scapular_Pull-Up e, Pullups h, Chin-Up h",
 "V-Bar_Pulldown": "Close-Grip_Front_Lat_Pulldown m, Wide-Grip_Lat_Pulldown m, One_Arm_Lat_Pulldown m, V-Bar_Pullup h",
 "Straight-Arm_Pulldown": "Rope_Straight-Arm_Pulldown m, Straight-Arm_Dumbbell_Pullover d, Bent-Arm_Barbell_Pullover d, Wide-Grip_Lat_Pulldown m",
 # ---------------- pull_h
 "Bent_Over_Barbell_Row": "T-Bar_Row_with_Handle d, One-Arm_Dumbbell_Row d, Bent_Over_Two-Dumbbell_Row d, Seated_Cable_Rows d, Leverage_Iso_Row d, Reverse_Grip_Bent-Over_Rows m",
 "One-Arm_Dumbbell_Row": "Bent_Over_Two-Dumbbell_Row m, Dumbbell_Incline_Row m, Seated_One-arm_Cable_Pulley_Rows d, One-Arm_Kettlebell_Row d, Bent_Over_Barbell_Row d",
 "Seated_Cable_Rows": "Leverage_Iso_Row d, Seated_One-arm_Cable_Pulley_Rows m, One-Arm_Dumbbell_Row d, Bent_Over_Barbell_Row d, Inverted_Row d",
 "T-Bar_Row_with_Handle": "Bent_Over_Barbell_Row d, Lying_T-Bar_Row m, Bent_Over_Two-Arm_Long_Bar_Row m, Seated_Cable_Rows d, Dumbbell_Incline_Row d",
 "Inverted_Row": "Inverted_Row_with_Straps m, Suspended_Row m, Seated_Cable_Rows d, One-Arm_Dumbbell_Row d, Bodyweight_Mid_Row e",
 "Leverage_Iso_Row": "Seated_Cable_Rows d, Leverage_High_Row m, Dumbbell_Incline_Row d, One-Arm_Dumbbell_Row d",
 "Dumbbell_Incline_Row": "One-Arm_Dumbbell_Row m, Incline_Bench_Pull m, Lying_T-Bar_Row d, Leverage_Iso_Row d, Seated_Cable_Rows d",
 "Face_Pull": "Cable_Rope_Rear-Delt_Rows m, Cable_Rear_Delt_Fly m, Reverse_Flyes d, Reverse_Machine_Flyes d, Band_Pull_Apart d",
 # ---------------- shoulders / arms iso
 "Side_Lateral_Raise": "Seated_Side_Lateral_Raise m, One-Arm_Side_Laterals m, Cable_Seated_Lateral_Raise d, Standing_Low-Pulley_Deltoid_Raise d, Lateral_Raise_-_With_Bands d",
 "Cable_Seated_Lateral_Raise": "Standing_Low-Pulley_Deltoid_Raise m, Side_Lateral_Raise d, Seated_Side_Lateral_Raise d, Lateral_Raise_-_With_Bands d",
 "Reverse_Flyes": "Seated_Bent-Over_Rear_Delt_Raise m, Cable_Rear_Delt_Fly d, Reverse_Machine_Flyes d, Face_Pull d, Band_Pull_Apart d",
 "Cable_Rear_Delt_Fly": "Face_Pull m, Reverse_Machine_Flyes d, Reverse_Flyes d, Band_Pull_Apart d",
 "Barbell_Curl": "EZ-Bar_Curl d, Dumbbell_Bicep_Curl d, Standing_Biceps_Cable_Curl d, Machine_Bicep_Curl d, Preacher_Curl m",
 "Dumbbell_Bicep_Curl": "Dumbbell_Alternate_Bicep_Curl m, Hammer_Curls m, Incline_Dumbbell_Curl m, Barbell_Curl d, Standing_Biceps_Cable_Curl d",
 "Hammer_Curls": "Alternate_Hammer_Curl m, Cross_Body_Hammer_Curl m, Cable_Hammer_Curls_-_Rope_Attachment d, Dumbbell_Bicep_Curl m",
 "Incline_Dumbbell_Curl": "Alternate_Incline_Dumbbell_Curl m, Dumbbell_Bicep_Curl m, Standing_Biceps_Cable_Curl d, Spider_Curl m",
 "Preacher_Curl": "Machine_Preacher_Curls d, Cable_Preacher_Curl d, Two-Arm_Dumbbell_Preacher_Curl d, Spider_Curl m, Concentration_Curls m",
 "EZ-Bar_Curl": "Close-Grip_EZ_Bar_Curl m, Barbell_Curl d, Dumbbell_Bicep_Curl d, Standing_Biceps_Cable_Curl d, Preacher_Curl m",
 "Triceps_Pushdown": "Triceps_Pushdown_-_Rope_Attachment m, Triceps_Pushdown_-_V-Bar_Attachment m, Machine_Triceps_Extension d, Tricep_Dumbbell_Kickback d, Bench_Dips d",
 "Triceps_Pushdown_-_Rope_Attachment": "Triceps_Pushdown m, Triceps_Pushdown_-_V-Bar_Attachment m, Triceps_Overhead_Extension_with_Rope m, Tricep_Dumbbell_Kickback d",
 "Triceps_Overhead_Extension_with_Rope": "Cable_Rope_Overhead_Triceps_Extension m, Standing_Dumbbell_Triceps_Extension d, Kettlebell_Overhead_Triceps_Extension d, EZ-Bar_Skullcrusher d",
 "EZ-Bar_Skullcrusher": "Lying_Dumbbell_Tricep_Extension d, Cable_Lying_Triceps_Extension d, Triceps_Overhead_Extension_with_Rope d, JM_Press m, Close-Grip_Barbell_Bench_Press m",
 "Dips_-_Triceps_Version": "Dip_Machine d, Close-Grip_Barbell_Bench_Press d, Triceps_Pushdown d, Bench_Dips e, Weighted_Bench_Dip m",
 "Barbell_Shrug": "Dumbbell_Shrug d, Leverage_Shrug d, Cable_Shrugs d, Smith_Machine_Behind_the_Back_Shrug d",
 "Dumbbell_Shrug": "Barbell_Shrug d, Leverage_Shrug d, Cable_Shrugs d, Calf-Machine_Shoulder_Shrug d",
 # ---------------- legs iso
 "Leg_Extensions": "Single-Leg_Leg_Extension m, Leg_Press m, Goblet_Squat m, Split_Squat_with_Dumbbells m",
 "Lying_Leg_Curls": "Seated_Leg_Curl m, Standing_Leg_Curl m, Ball_Leg_Curl d, Romanian_Deadlift m, Glute_Ham_Raise h",
 "Seated_Leg_Curl": "Lying_Leg_Curls m, Standing_Leg_Curl m, Seated_Band_Hamstring_Curl d, Ball_Leg_Curl d, Glute_Ham_Raise h",
 "Standing_Calf_Raises": "Smith_Machine_Calf_Raise d, Standing_Dumbbell_Calf_Raise d, Calf_Press_On_The_Leg_Press_Machine d, Donkey_Calf_Raises m, Seated_Calf_Raise m",
 "Seated_Calf_Raise": "Barbell_Seated_Calf_Raise d, Dumbbell_Seated_One-Leg_Calf_Raise d, Standing_Calf_Raises m, Calf_Press m",
 "Thigh_Abductor": "Monster_Walk d, Lying_Crossover m",
 "Thigh_Adductor": "Cable_Hip_Adduction d, Band_Hip_Adductions d, Plie_Dumbbell_Squat m",
 "Glute_Ham_Raise": "Natural_Glute_Ham_Raise d, Floor_Glute-Ham_Raise d, Romanian_Deadlift m, Lying_Leg_Curls e",
 # ---------------- core
 "Plank": "Dead_Bug e, Side_Bridge m, Pallof_Press d, Push_Up_to_Side_Plank h, Ab_Roller h",
 "Side_Bridge": "Pallof_Press d, Plank m, Push_Up_to_Side_Plank h",
 "Dead_Bug": "Plank m, Reverse_Crunch m, Pallof_Press d, Flat_Bench_Lying_Leg_Raise h",
 "Pallof_Press": "Side_Bridge d, Standing_Cable_Wood_Chop m, Plank d, Pallof_Press_With_Rotation h",
 "Cable_Crunch": "Ab_Crunch_Machine d, Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists m, Weighted_Crunches d, Crunches e",
 "Hanging_Leg_Raise": "Knee_Hip_Raise_On_Parallel_Bars e, Cable_Reverse_Crunch d, Flat_Bench_Lying_Leg_Raise e, Reverse_Crunch e",
 "Ab_Roller": "Barbell_Ab_Rollout d, Suspended_Fallout d, Exercise_Ball_Pull-In d, Plank e",
 "Russian_Twist": "Cable_Russian_Twists d, Plate_Twist d, Standing_Cable_Wood_Chop d, Pallof_Press_With_Rotation d",
 "Reverse_Crunch": "Flat_Bench_Lying_Leg_Raise m, Cable_Reverse_Crunch d, Dead_Bug e, Decline_Reverse_Crunch h, Hanging_Leg_Raise h",
 "Crunches": "Exercise_Ball_Crunch m, Dead_Bug m, Cable_Crunch d, Ab_Crunch_Machine d, Weighted_Crunches h",
 # ---------------- carry / cardio
 "Farmers_Walk": "Yoke_Walk d, Rickshaw_Carry d",
 "Walking_Treadmill": "Trail_Running_Walking d, Elliptical_Trainer d, Recumbent_Bike e, Stairmaster h, Jogging_Treadmill h",
 "Running_Treadmill": "Jogging_Treadmill e, Trail_Running_Walking d, Rowing_Stationary d, Elliptical_Trainer e, Bicycling_Stationary d",
 "Bicycling_Stationary": "Recumbent_Bike e, Bicycling d, Elliptical_Trainer d, Rowing_Stationary d, Air_Bike h",
 "Rowing_Stationary": "Bicycling_Stationary d, Elliptical_Trainer d, Air_Bike d, Running_Treadmill d",
 "Elliptical_Trainer": "Bicycling_Stationary d, Walking_Treadmill e, Stairmaster d, Rowing_Stationary d",
 "Stairmaster": "Step_Mill m, Elliptical_Trainer e, Walking_Treadmill e, Bicycling_Stationary d",
 "Rope_Jumping": "Running_Treadmill d, Battling_Ropes d, Jogging_Treadmill e",
 "Recumbent_Bike": "Bicycling_Stationary h, Elliptical_Trainer d, Walking_Treadmill d",
 "Battling_Ropes": "Air_Bike d, Rowing_Stationary d, Rope_Jumping d",
 "Air_Bike": "Bicycling_Stationary e, Rowing_Stationary d, Battling_Ropes d",
}

CUES = {
 "Barbell_Squat": ["Brace your core before you unrack", "Knees track over your toes", "Sit down between your hips, chest up", "Drive through the whole foot to stand"],
 "Barbell_Full_Squat": ["Big breath and brace at the top", "Go as deep as you can keep a neutral back", "Knees out over toes", "Drive up through mid-foot"],
 "Front_Squat_Clean_Grip": ["Elbows high, bar on the front of the shoulders", "Stay upright as you sit down", "Knees forward and out", "Keep elbows up as you stand"],
 "Goblet_Squat": ["Hold the weight at your chest", "Elbows inside the knees at the bottom", "Chest tall, sit straight down", "Push the floor away"],
 "Leg_Press": ["Feet shoulder-width, flat on the platform", "Lower until your hips start to tuck, no further", "Don't lock the knees at the top", "Keep your lower back on the pad"],
 "Hack_Squat": ["Back flat against the pad", "Feet mid-platform, shoulder-width", "Lower under control to a deep bend", "Drive through heels and mid-foot"],
 "Smith_Machine_Squat": ["Feet slightly in front of the bar", "Brace before unlocking", "Sit down with control", "Push the floor away"],
 "Bodyweight_Squat": ["Arms forward for balance", "Hips back and down", "Knees follow the toes", "Stand tall and squeeze glutes at the top"],
 "Dumbbell_Squat": ["Dumbbells hang at your sides", "Chest up, brace", "Sit down between the heels", "Drive up through the whole foot"],
 "Box_Squat": ["Sit back to the box with control", "Pause briefly, stay tight", "Don't relax or rock on the box", "Drive up hard"],
 "Barbell_Deadlift": ["Bar over mid-foot, shins close", "Pull the slack out before you lift", "Push the floor away, bar stays close", "Stand tall, don't lean back"],
 "Romanian_Deadlift": ["Soft knees, push hips back", "Bar slides down the thighs", "Stop when hamstrings are stretched and back is flat", "Squeeze glutes to stand"],
 "Trap_Bar_Deadlift": ["Stand centred in the bar", "Chest up, hips down to the handles", "Push through the floor", "Lock out with glutes, not the lower back"],
 "Stiff-Legged_Dumbbell_Deadlift": ["Slight knee bend, stays fixed", "Hinge from the hips", "Dumbbells close to the legs", "Flat back throughout"],
 "Barbell_Hip_Thrust": ["Upper back on the bench edge", "Tuck chin, ribs down", "Drive hips up to a straight line", "Pause and squeeze at the top"],
 "Barbell_Glute_Bridge": ["Feet flat, close to your bum", "Brace, then drive hips up", "Squeeze glutes at the top", "Lower with control"],
 "Single_Leg_Glute_Bridge": ["Working heel close to your bum", "Keep hips level", "Drive up through the heel", "Squeeze at the top"],
 "Hyperextensions_Back_Extensions": ["Pad just below the hip bones", "Hinge from the hips", "Rise to a straight line, don't overarch", "Move slowly"],
 "Good_Morning": ["Bar on upper back, soft knees", "Push hips back", "Keep your back flat", "Start light"],
 "One-Arm_Kettlebell_Swings": ["Hike the bell back between the legs", "Snap the hips forward", "Arm guides, hips power", "Don't squat it, hinge it"],
 "Sumo_Deadlift": ["Wide stance, toes out", "Grip inside the knees", "Push knees out, chest up", "Push the floor apart as you stand"],
 "Pull_Through": ["Face away from the cable, rope between the legs", "Hinge back, arms long", "Snap hips forward to stand", "Squeeze glutes at lockout"],
 "Kettlebell_One-Legged_Deadlift": ["Slight bend in the standing knee", "Back leg rises as you hinge", "Hips square to the floor", "Move slowly, own the balance"],
 "Dumbbell_Lunges": ["Step long enough that both knees reach about 90°", "Torso upright", "Front knee over the foot", "Push back through the front heel"],
 "Barbell_Walking_Lunge": ["Bar on upper back, brace", "Controlled steps", "Back knee close to the floor", "Drive through the front foot"],
 "Bodyweight_Walking_Lunge": ["Hands on hips", "Long, controlled steps", "Keep torso upright", "Push through the front heel"],
 "Split_Squat_with_Dumbbells": ["Staggered stance, feet stay put", "Drop the back knee straight down", "Front knee tracks over toes", "Drive up through the front foot"],
 "Dumbbell_Step_Ups": ["Whole foot on the box", "Drive with the top leg, not the back leg", "Stand tall at the top", "Step down slowly"],
 "Dumbbell_Rear_Lunge": ["Step back, not sideways", "Lower the back knee under control", "Weight in the front heel", "Push back to standing"],
 "Barbell_Lunge": ["Bar on upper back, brace", "Step forward with control", "Torso upright", "Push back through the front heel"],
 "Barbell_Bench_Press_-_Medium_Grip": ["Shoulder blades squeezed together, feet planted", "Lower to lower chest", "Elbows about 45° from the body", "Press up and slightly back"],
 "Dumbbell_Bench_Press": ["Shoulder blades back and down", "Lower until elbows are just below the bench", "Wrists stacked over elbows", "Press up and together"],
 "Incline_Dumbbell_Press": ["Bench at 30-45°", "Shoulder blades pinned", "Lower to upper chest level", "Press up, don't clash the weights"],
 "Barbell_Incline_Bench_Press_-_Medium_Grip": ["Bench at 30-45°", "Lower to the upper chest", "Elbows slightly tucked", "Press straight up"],
 "Pushups": ["Hands just wider than shoulders", "Body in a straight line", "Chest to just above the floor", "Elbows at about 45°"],
 "Incline_Push-Up": ["Hands on a bench or bar", "Body in a straight line", "Chest to the edge", "Lower the height as you get stronger"],
 "Machine_Bench_Press": ["Handles level with mid-chest", "Shoulder blades against the pad", "Press without locking out hard", "Control the return"],
 "Cable_Crossover": ["Slight forward lean, soft elbows", "Sweep hands together in an arc", "Squeeze the chest", "Return slowly to a stretch"],
 "Dumbbell_Flyes": ["Slight bend in the elbows, fixed", "Open wide to a chest stretch", "Hug a big tree on the way up", "Don't go heavy"],
 "Dips_-_Chest_Version": ["Lean forward slightly", "Lower until shoulders are just below elbows", "Don't sink into the shoulders", "Press back up"],
 "Close-Grip_Barbell_Bench_Press": ["Hands about shoulder-width", "Elbows tucked close", "Lower to lower chest", "Press with triceps"],
 "Leverage_Chest_Press": ["Adjust seat so handles meet mid-chest", "Back and shoulders on the pad", "Press smoothly", "Control the return"],
 "Butterfly": ["Adjust seat so arms are level with the chest", "Soft elbows", "Squeeze together", "Slow return"],
 "Smith_Machine_Bench_Press": ["Bar lines up with lower chest", "Shoulder blades back", "Lower under control", "Press up"],
 "Standing_Military_Press": ["Squeeze glutes, brace the core", "Bar starts on upper chest", "Press straight up, head through at the top", "Don't lean back"],
 "Dumbbell_Shoulder_Press": ["Dumbbells at shoulder height", "Brace, ribs down", "Press up without clashing", "Lower with control"],
 "Seated_Dumbbell_Press": ["Back against the upright pad", "Start at shoulder height", "Press up and slightly in", "Don't arch the lower back"],
 "Machine_Shoulder_Military_Press": ["Handles at shoulder height", "Back on the pad", "Press up smoothly", "Control the lowering"],
 "Arnold_Dumbbell_Press": ["Start palms facing you", "Rotate as you press", "Finish palms forward overhead", "Reverse on the way down"],
 "Landmine_Linear_Jammer": ["Bar end at shoulder height", "Staggered or square stance, brace", "Press up and forward", "Control the return"],
 "Pullups": ["Start from a dead hang, shoulders engaged", "Pull elbows down to your sides", "Chin over the bar", "Lower all the way"],
 "Chin-Up": ["Palms facing you, shoulder-width", "Pull chest to the bar", "Keep legs quiet", "Full hang at the bottom"],
 "Wide-Grip_Lat_Pulldown": ["Thighs locked under the pad", "Pull the bar to upper chest", "Drive elbows down and back", "Don't lean back much"],
 "Close-Grip_Front_Lat_Pulldown": ["Chest up", "Pull to upper chest", "Elbows down and in", "Full stretch at the top"],
 "Band_Assisted_Pull-Up": ["Loop band on bar, knee or foot in", "Start from a full hang", "Pull chin over the bar", "Use a lighter band as you get stronger"],
 "V-Bar_Pulldown": ["Slight lean back", "Pull handle to upper chest", "Squeeze shoulder blades down", "Controlled return"],
 "Straight-Arm_Pulldown": ["Slight hinge, arms nearly straight", "Sweep the bar to your thighs", "Feel it in the lats", "Slow on the way up"],
 "Bent_Over_Barbell_Row": ["Hinge to about 45°, flat back", "Pull the bar to your lower ribs", "Squeeze shoulder blades", "Don't jerk with the hips"],
 "One-Arm_Dumbbell_Row": ["Hand and knee on the bench, flat back", "Pull the dumbbell to your hip", "Elbow close to the body", "Full stretch at the bottom"],
 "Seated_Cable_Rows": ["Sit tall, slight knee bend", "Pull the handle to your belly", "Squeeze shoulder blades together", "Let them stretch forward slowly"],
 "T-Bar_Row_with_Handle": ["Hinge, flat back", "Pull handle to the chest", "Elbows back", "Control the lowering"],
 "Inverted_Row": ["Body in a straight line", "Pull chest to the bar", "Squeeze shoulder blades", "Walk feet back to make it easier"],
 "Leverage_Iso_Row": ["Chest against the pad", "Pull elbows back", "Squeeze at the end", "Slow return"],
 "Dumbbell_Incline_Row": ["Chest on an incline bench", "Arms hang straight down", "Row elbows back", "No bouncing off the bench"],
 "Face_Pull": ["Rope at face height", "Pull towards your eyes, hands apart", "Elbows high", "Squeeze the back of the shoulders"],
 "Side_Lateral_Raise": ["Slight bend in the elbows", "Raise out to the side to shoulder height", "Lead with the elbows", "Lower slowly"],
 "Cable_Seated_Lateral_Raise": ["Cable at the lowest setting", "Raise out to shoulder height", "Constant tension, no swinging", "Lower slowly"],
 "Reverse_Flyes": ["Hinge forward, flat back", "Soft elbows", "Open arms out to the side", "Squeeze the rear shoulders"],
 "Cable_Rear_Delt_Fly": ["Cables crossed at shoulder height", "Pull out and back", "Arms nearly straight", "Squeeze, then slow return"],
 "Barbell_Curl": ["Elbows pinned to your sides", "Curl without swinging", "Squeeze at the top", "Lower all the way"],
 "Dumbbell_Bicep_Curl": ["Elbows by your sides", "Turn palms up as you curl", "No swinging", "Slow on the way down"],
 "Hammer_Curls": ["Palms facing each other", "Elbows still", "Curl to shoulder height", "Lower with control"],
 "Incline_Dumbbell_Curl": ["Bench at about 45°, arms hang back", "Keep elbows still", "Curl up", "Full stretch at the bottom"],
 "Preacher_Curl": ["Armpits snug to the pad", "Curl up without lifting elbows", "Don't fully relax at the bottom", "Lower slowly"],
 "EZ-Bar_Curl": ["Grip the angled part of the bar", "Elbows pinned", "Curl and squeeze", "Lower fully"],
 "Triceps_Pushdown": ["Elbows pinned to your sides", "Push down until arms are straight", "Squeeze the triceps", "Only the forearms move"],
 "Triceps_Pushdown_-_Rope_Attachment": ["Elbows by your sides", "Push down and spread the rope", "Lock out and squeeze", "Slow return"],
 "Triceps_Overhead_Extension_with_Rope": ["Face away from the cable, rope behind the head", "Elbows point forward", "Extend arms fully", "Stretch on the way back"],
 "EZ-Bar_Skullcrusher": ["Upper arms angled slightly back", "Lower the bar towards your forehead", "Only the elbows bend", "Extend fully"],
 "Dips_-_Triceps_Version": ["Stay upright", "Elbows track back", "Lower to about 90° at the elbow", "Press to lockout"],
 "Barbell_Shrug": ["Arms straight", "Shrug straight up towards your ears", "Pause at the top", "No rolling"],
 "Dumbbell_Shrug": ["Dumbbells at your sides", "Shrug straight up", "Hold for a second", "Lower fully"],
 "Leg_Extensions": ["Knee lines up with the machine pivot", "Extend fully", "Squeeze the quads", "Slow on the way down"],
 "Lying_Leg_Curls": ["Knees just off the bench edge", "Hips stay down", "Curl heels to your bum", "Lower slowly"],
 "Seated_Leg_Curl": ["Knee in line with the pivot", "Thigh pad snug", "Curl all the way back", "Control the return"],
 "Standing_Calf_Raises": ["Balls of the feet on the edge", "Full stretch at the bottom", "Rise as high as you can", "Pause at the top"],
 "Seated_Calf_Raise": ["Pad on the lower thigh", "Drop the heels fully", "Push up onto your toes", "Pause at top and bottom"],
 "Thigh_Abductor": ["Sit tall against the pad", "Push knees out", "Pause at the widest point", "Slow return"],
 "Thigh_Adductor": ["Sit tall", "Squeeze legs together", "Pause at the middle", "Let them open slowly"],
 "Glute_Ham_Raise": ["Knees just behind the pad", "Body straight from knees to head", "Lower slowly using hamstrings", "Pull back up with hamstrings"],
 "Plank": ["Elbows under shoulders", "Straight line head to heels", "Squeeze glutes, brace the belly", "Breathe normally"],
 "Side_Bridge": ["Elbow under shoulder", "Hips up in a straight line", "Don't let hips sag", "Breathe"],
 "Dead_Bug": ["Lower back pressed to the floor", "Opposite arm and leg lower slowly", "Only go as low as you can stay flat", "Breathe out as you extend"],
 "Pallof_Press": ["Stand side-on to the cable", "Press hands straight out", "Resist the twist", "Hold, then return"],
 "Cable_Crunch": ["Kneel, rope by your head", "Curl your ribs towards your hips", "Hips stay still", "Slow return"],
 "Hanging_Leg_Raise": ["Dead hang, shoulders engaged", "Raise legs without swinging", "Curl the pelvis up at the top", "Lower slowly"],
 "Ab_Roller": ["Start on your knees", "Brace hard, roll out slowly", "Keep hips in line, don't sag", "Pull back with your abs"],
 "Russian_Twist": ["Lean back slightly, chest up", "Rotate from the ribs", "Touch each side", "Keep it controlled"],
 "Reverse_Crunch": ["Knees bent at 90°", "Curl hips up off the floor", "Don't swing the legs", "Lower slowly"],
 "Crunches": ["Hands lightly by your head", "Curl ribs towards hips", "Lower back stays down", "Don't pull on the neck"],
 "Farmers_Walk": ["Stand tall, shoulders back", "Brace the core", "Short, quick steps", "Grip hard"],
 "Walking_Treadmill": ["Stand tall, arms swinging naturally", "Don't hold the rails", "Use the incline to raise effort", "Aim for a pace where you can still talk"],
 "Running_Treadmill": ["Relaxed shoulders", "Quick, light steps under your body", "Don't hold the rails", "Build pace gradually"],
 "Bicycling_Stationary": ["Seat at hip height when standing", "Slight knee bend at the bottom of the stroke", "Steady cadence", "Adjust resistance for effort"],
 "Rowing_Stationary": ["Legs, then body, then arms", "Arms, body, then legs on the way back", "Keep the back flat", "Power comes from the legs"],
 "Elliptical_Trainer": ["Stand tall", "Push and pull with the arms", "Keep the whole foot on the pedals", "Use resistance, not just speed"],
 "Stairmaster": ["Stand upright", "Light hands on the rails only", "Whole foot on each step", "Steady rhythm"],
 "Rope_Jumping": ["Turn the rope from the wrists", "Small jumps on the balls of the feet", "Elbows close to your sides", "Land softly"],
 "Recumbent_Bike": ["Seat set so knee is slightly bent at full extension", "Back against the rest", "Steady cadence", "Adjust resistance for effort"],
 "Battling_Ropes": ["Athletic stance, knees bent", "Brace the core", "Waves from the shoulders", "Keep the rhythm"],
 "Air_Bike": ["Push and pull with arms and legs", "Stay seated and tall", "Pace your effort", "Use for short hard intervals"],
}
