// Re-export icons from the design canvas. Run after re-exporting design/canvas:
//   npm run extract -w @tare/icons
// Reads Icons.dc.html (read-only) and vpt/data/exercises.json enums, and writes
// src/generated/*.ts. The output is committed; review the diff by eye.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkg = join(dirname(fileURLToPath(import.meta.url)), '..');
const repo = join(pkg, '../..');
const html = readFileSync(join(repo, 'design/canvas/Icons.dc.html'), 'utf8');

type Node = [tag: string, attrs: Record<string, string | number>];

const GEOMETRY = new Set([
  'd',
  'cx',
  'cy',
  'r',
  'rx',
  'ry',
  'x',
  'y',
  'x1',
  'y1',
  'x2',
  'y2',
  'width',
  'height',
  'points',
]);

/** Child elements of an <svg>, keeping geometry only (colour comes from props/tokens). */
function nodes(svg: string, keepFill = false): Node[] {
  const inner = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>$/, '');
  return [...inner.matchAll(/<([a-z]+)([^>]*?)\/?>/g)]
    .filter((m) => !m[0].startsWith('</'))
    .map((m) => {
      const attrs: Record<string, string | number> = {};
      for (const a of (m[2] as string).matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) {
        const [k, v] = [a[1] as string, a[2] as string];
        if (GEOMETRY.has(k) || (keepFill && k === 'fill')) {
          attrs[k] = /^-?\d+(\.\d+)?$/.test(v) ? Number(v) : v;
        } else if (k === 'fill' && v !== 'none') {
          // A filled dot inside a stroked icon (e.g. "more"): keep it filled with currentColor.
          attrs['fill'] = 'currentColor';
        }
      }
      return [m[1] as string, attrs] as Node;
    });
}

const svgs = [...html.matchAll(/<svg[\s\S]*?<\/svg>/g)].map((m) => ({
  svg: m[0],
  // The label that follows each icon on the board.
  label: html
    .slice((m.index ?? 0) + m[0].length, (m.index ?? 0) + m[0].length + 400)
    .replace(/<[^>]+>/g, '|')
    .split('|')
    .map((s) => s.trim())
    .filter(Boolean),
}));

const patterns: Record<string, Node[]> = {};
const ui: Record<string, Node[]> = {};
const bodies: Node[][] = [];

for (const { svg, label } of svgs) {
  const code = label.find((l) => l.startsWith('icon.m-'));
  if (code) {
    patterns[code.replace('icon.m-', '')] = nodes(svg);
  } else if (svg.includes('viewBox="0 0 60 150"')) {
    bodies.push(nodes(svg, true));
  } else if (svg.includes('viewBox="0 0 24 24"') && label[0]) {
    ui[label[0]] = nodes(svg);
  }
}

// Muscle map. All 4 front drawings share geometry, as do the 4 back ones; only fills
// change. Region → vpt muscle, worked out from which shapes light up for squat, bench,
// lat pulldown and deadlift on the board. Index = shape order in the SVG.
const FRONT = [
  null, // head
  'shoulders',
  'shoulders',
  'chest',
  'chest',
  'abdominals',
  'biceps',
  'biceps',
  'forearms',
  'forearms',
  'quadriceps',
  'quadriceps',
  'calves', // shins: the enum has no tibialis, so front lower leg shows calves
  'calves',
];
const BACK = [
  null, // head
  'traps',
  'shoulders',
  'shoulders',
  'lats',
  'lats',
  'middle back',
  'lower back',
  'triceps',
  'triceps',
  'forearms',
  'forearms',
  'glutes',
  'glutes',
  'hamstrings',
  'hamstrings',
  'calves',
  'calves',
];
const [front, back] = [bodies[0], bodies[1]];
if (bodies.length !== 8 || front?.length !== FRONT.length || back?.length !== BACK.length) {
  throw new Error('Muscle map shape count changed on the canvas: update FRONT/BACK mapping');
}
const region = (n: Node, i: number, map: (string | null)[]) => {
  const attrs = { ...n[1] };
  delete attrs['fill'];
  return { tag: n[0], attrs, muscle: map[i] ?? null };
};

const enums = JSON.parse(readFileSync(join(repo, 'vpt/data/exercises.json'), 'utf8')).enums as {
  muscles: string[];
  movement_pattern: string[];
};

const header =
  '// Generated by scripts/extract.ts from design/canvas/Icons.dc.html. Do not edit.\n';
const lit = (v: unknown) => JSON.stringify(v, null, 2);

writeFileSync(
  join(pkg, 'src/generated/icons.ts'),
  `${header}import type { IconNode } from '../types.ts';

export const uiIcons = ${lit(ui)} as const satisfies Record<string, readonly IconNode[]>;

/** Canvas pattern codes (icon.m-*). */
export const patternIcons = ${lit(patterns)} as const satisfies Record<string, readonly IconNode[]>;

export const muscleMapFront = ${lit(front.map((n, i) => region(n, i, FRONT)))} as const;

export const muscleMapBack = ${lit(back.map((n, i) => region(n, i, BACK)))} as const;
`,
);

writeFileSync(
  join(pkg, 'src/generated/enums.ts'),
  `// Generated by scripts/extract.ts from vpt/data/exercises.json → enums. Do not edit.
export const muscles = ${lit(enums.muscles)} as const;
export type Muscle = (typeof muscles)[number];

export const movementPatterns = ${lit(enums.movement_pattern)} as const;
export type MovementPattern = (typeof movementPatterns)[number];
`,
);

console.log(
  `icons: ${Object.keys(ui).length} UI, ${Object.keys(patterns).length} patterns, muscle map ${front.length}+${back.length} regions`,
);
